### ISSUE TITLE
Plugin does not encode non ASCII chars

### ISSUE THREAD

**Issue by carusog** [azz/vscode-csproj#17]
Trying to add a file to the project with `@` in the path name, I didn't get the non ASCII character encoded.
The issue caused Visual Studio to see two files in the solution, actually pointing to the same file on disk.

```xml
// E.G.

// expected
<TypeScriptCompile Include="path\to\my\file\%40folder\file-name.service.ts" />
// got
<TypeScriptCompile Include="path\to\my\file\@folder\file-name.service.ts" />
```

Visual Studio v. 15.4.1 (Community Edition)
Visual Studio Code v. 1.18.0

**Comment by azz** [comment]
Fixed in #18
