### ISSUE TITLE
Dynamic Item Type

### ISSUE THREAD

**Issue by conner-fallone** [azz/vscode-csproj#2]
It would be nice if the item type was dynamic rather than having to be hard coded. For example, we have a combination of .ts and .js files, When adding a .ts file, it should be TypeScriptCompile item type, but javascript should be content.

**Comment by azz** [comment]
How about a config mapping from file extension to content type? 

e.g.:

``` json
"csproj.itemType": {
  "*": "Content",
  "ts": "TypeScriptCompile"
}
```

**Comment by conner-fallone** [comment]
That would work!

**Comment by conner-fallone** [comment]
Also would just like to tack this on here instead of creating a new issue, but our .csproj has multiple ItemGroup tags. Not sure how VS determines which ItemGroup a file goes to in the .csproj, but where this extension places it seems to be out of place from where VS put's all of our other files. Any idea what is going on here?

**Comment by azz** [comment]
@fallXone I haven't really done any experimentation with Visual Studio to figure that out. At the moment I am just adding it to the last `ItemGroup` in the file. The order doesn't seem too important.

**Comment by azz** [comment]
Feature implemented with `0.5.1` a74a11888a57fee82e2ce6618f13a7936d73dc03.

Note that the configuration object requires a leading dot, e.g. `.ts`.

**Comment by saintplay** [comment]
This is very nice.   
There is any chance to get `".cs": "Compile"` in the default map?

**Comment by azz** [comment]
Opened #10
