### ISSUE TITLE
Sources added to project file but not compiled.

### ISSUE THREAD

**Issue by ljsnogard** [azz/vscode-csproj#20]
After popup and added the source into the project file (.csproj), source file is listed in vs project navigator.
However when compiling, the "added files" are missing.

I see the difference in the project file.

Below is added by the plugin:
```
<Content Include="MySource.cs">
```

After changing line to below:
```
<Compile Include="MySource.cs"> 
```

The project build can succeed.

**Comment by szyb** [comment]
Try add to settings (File->Preferences->Settings):
`"csproj.itemType": {
        ".cs" : "Compile"
    },`
After that add new file and it will be added within "Compile" node

**Comment by ljsnogard** [comment]
It works as expected.
Thank you for your great job!

**Comment by gswebspace** [comment]
Can this be made the default option ? Why else would you add a ".cs" file and not have it compiled ?
