### ISSUE TITLE
Support for other *proj extension

### ISSUE THREAD

**Issue by jRichardeau** [azz/vscode-csproj#26]
Hi,
Could this extension support other project files (like njsproj) ?
Or have I to do a fork ?

Thank you

**Comment by cmeyertons** [comment]
Seconding this -- would be super useful for other projects, like `*.sqlproj`

**Comment by cspaniard** [comment]
I agree... about .fsproj ?

**Comment by azz** [comment]
Sorry but I haven't really been able to maintain this extension, and I don't use it anymore.

I would recommend forking 😞

**Comment by jRichardeau** [comment]
@cmeyertons @cspaniard 
FYI I've made a fork and I published a new extension here : https://marketplace.visualstudio.com/items?itemName=jRichardeau.vscode-vsproj

It works a bit different from this one (no prompt anymore for instance).

The extension should work for any type of VS project file when configured (csproj, njsproj, sqlproj etc) but I've only tested it for njsproj.

I would be happy if you could (and want to) test it and give me feedback !
