### ISSUE TITLE
Removing file from .csproj

### ISSUE THREAD

**Issue by conner-fallone** [azz/vscode-csproj#3]
Would it be possible to add support for removing from .csproj when a file is deleted?

**Comment by azz** [comment]
I think so. It could be done with a file watcher listening to deletes. Question is do you do it silently, or prompt each time? What about when you change git branch? It may behave inappropriately.

**Comment by azz** [comment]
One possible solution would be to debounce the prompt. 

e.g.:

I delete one file, wait two seconds, then:

> FileX.ts was deleted. Remove it from Proj.csproj?  **[ Yes ] [ Close ]**

I switch branch, which removes 10 files from my workspace, then:

> 10 files were deleted. Remove them from csproj? **[ Yes ] [ Close ]**

Thoughts?

**Comment by conner-fallone** [comment]
It seems like the best solution would be to do it silently. Not sure why you would delete a file and expect it to still be in your .csproj, this brings up another point though of what happens when you move a file. i would expect that to also silently update the .csproj. You can also add an exclude from csproj option in the context menu.

**Comment by azz** [comment]
I've implemented the behaviour from my comment above, but I'm happy to make it configurable.

Handling moved files is a little trickier. They appear as a deletion followed by a creation. There are some heuristics I could use to determine a moved file, but there may be hidden bugs. I'll have to think about that one.

**Comment by conner-fallone** [comment]
You probably want to include the user's excluded files as well if you can gain access to those? I exclude one of my folders since we use grunt, and now this extension picks up on a bunch of files grunt is deleting that I don't care about, and would never be in my csproj

**Comment by azz** [comment]
`files.exclude`? Good idea, should be possible. I think I'd have to re-implement some behavior such as `"*.js": { "when": "$(basename).ts" }` though.

As a stop gap you can use `excludeRegex` with the file path you do not want added.

**Comment by azz** [comment]
@fallXone Implemented in 0.6.1. Turned out to be super simple, and I got to delete some of my file walking code.
