### ISSUE TITLE
Include sub-foler

### ISSUE THREAD

**Issue by StephaneG31** [azz/vscode-csproj#7]
Sometimes I re-import a complete folders tree with some changes on subdir.
When I right-click then include, no changes appears on csproj, I must right-click then include each individual subdir with new fil.
Idem for remove.
Can you add subdir management changes ?

**Comment by azz** [comment]
Should be fixed with version [0.6.6](/DerFlatulator/vscode-csproj/releases/tag/v0.6.6).

**Comment by StephaneG31** [comment]
Thanks for your reactivity !

**Comment by rapasoft** [comment]
Hi, I am using version 0.6.6 of your plugin, but there's this issue again, it only searches files up to 2nd level of directory. Then I need to individually click on each of the nested directories. I'm not sure, but it might have something with this expression: https://github.com/azz/vscode-csproj/blob/v0.6.6/src/extension.ts#L179 ?
