### ISSUE TITLE
Files Not Being Detected In csproj File

### ISSUE THREAD

**Issue by mlturner88** [azz/vscode-csproj#9]
Nearly any file I open it cannot detect in the csproj file. It is successfully detecting the correct csproj file to look inside of but something is preventing it from recognizing that it is in there or not. I've attached an example.

![image](https://user-images.githubusercontent.com/6932385/27498797-b6c795a4-582e-11e7-99e7-6a1f3aa64150.png)
![image](https://user-images.githubusercontent.com/6932385/27498846-f0a43fe8-582e-11e7-9fa7-e5618d57b92a.png)

**Comment by azz** [comment]
It's almost certainly due to the forward slash in `app/`. Try changing them to `app\est\core\...`.

**Comment by mlturner88** [comment]
> It's almost certainly due to the forward slash in app/. Try changing them to app\est\core\....

That solved the issue. Thanks for the feedback!
